services:
  # Full Stack Application (Backend + Frontend)
  - type: web
    name: vigyapana
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run render-start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: vigyapana-mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        value: https://vigyapana.onrender.com
      - key: ADMIN_EMAIL
        value: admin@vigyapana.com
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: VITE_API_URL
        value: https://vigyapana.onrender.com

databases:
  - name: vigyapana-mongodb
    databaseName: vigyapana
    user: vigyapana-user
